### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'multi_process'

### ISSUE THREAD

**Issue by horagong** [ros-visualization/rqt_graph#15]
I compiled 0.4.10 version.
When I do rqt_graph, it fails.
```
Traceback (most recent call last):
  File "/opt/ros/lunar/bin/rqt_graph", line 8, in <module>
    sys.exit(main.main(sys.argv, standalone='rqt_graph.ros_graph.RosGraph'))
  File "/opt/ros/lunar/lib/python2.7/site-packages/rqt_gui/main.py", line 59, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider, plugin_manager_settings_prefix=str(hash(os.environ['ROS_PACKAGE_PATH'])))
  File "/opt/ros/lunar/lib/python2.7/site-packages/qt_gui/main.py", line 416, in main
    plugin_manager = PluginManager(plugin_provider, settings, context, settings_prefix=plugin_manager_settings_prefix)
  File "/opt/ros/lunar/lib/python2.7/site-packages/qt_gui/plugin_manager.py", line 82, in __init__
    if self._application_context.options.multi_process or self._application_context.options.embed_plugin:
AttributeError: 'Namespace' object has no attribute 'multi_process'
```

I just moved `self._options.multi_process = False  # not supported anymore`, line 416,  like the following. It seems ok. 
```
        if standalone:
            # rerun parsing to separate common arguments from plugin specific arguments
            parser = ArgumentParser(os.path.basename(Main.main_filename), add_help=False)
            self.add_arguments(parser, standalone=bool(standalone))
            self._options, plugin_args = parser.parse_known_args(arguments)
        self._options.plugin_args = plugin_args

        self._options.multi_process = False  # not supported anymore  
```
Hmm.. It is not rqt_graph error. It's due to qt_gui.

**Comment by dirk-thomas** [comment]
I think this problem has been fixed by ros-visualization/qt_gui_core#116.

Please try the latest version of `qt_gui` which is 0.3.9. If the Debian package isn't available yet you can compile the package from source.

Assuming that the problem has already been addressed I will go ahead and close this ticket. Please feel free to comment and the ticket can be reopened if necessary.

**Comment by kartikmohta** [comment]
This problem still persists, see https://github.com/ros-visualization/qt_gui_core/pull/116#issuecomment-410552099.
