### ISSUE TITLE
ValueError: PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by 8krisv** [ros-visualization/rqt_graph#58]
I installed ROS noetic for ubuntu 20.04 following the steps presented on the next page:  http://wiki.ros.org/noetic/Installation/Ubuntu, but the rqt command is not working for me and it always shows the following error

-->rqt
Traceback (most recent call last):
  File "/opt/ros/noetic/bin/rqt", line 13, in <module>
    sys.exit(main.main())
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/main.py", line 61, in main
    return super(
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/main.py", line 407, in main
    from python_qt_binding import QT_BINDING
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/__init__.py", line 55, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 274, in <module>
    _select_qt_binding(
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 155, in _load_pyqt
    _named_optional_import('PyQt5.%s' % module_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 142, in _named_optional_import
    _named_import(name)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 133, in _named_import
    module = builtins.__import__(name)
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by 8krisv** [comment]
problem solved by uninstalling PyQt5 and PyQt5-sip with pip3

**Comment by g3grau** [comment]
same here :) 
When trying to reinstall, pyqt5 was already/still present as system-wide installation, while pyqt5-sip reinstalled as user without breaking rqt plugins. Probably some outdated user-based installation of pyqt5 interfering with the system-wide version?
